name: "Monthly Job"

on:
  workflow_dispatch:
  schedule:
    # 毎月10日の9時に実行
    - cron: "0 9 10 * *"
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Test
        run: echo $EMAIL
        env:
          EMAIL: ${{ secrets.EMAIL }}
      - name: Run script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          LINE_ACCESS_TOKEN: ${{ secrets.LINE_ACCESS_TOKEN }}
        run: node dist/index.js
